'use client';
import {useEffect,useState} from 'react';
type Task={id:string;name:string;detail:string;min:number;done:boolean};
type Word={word:string;zh:string;def:string;collocation:string;example:string;error:string;sentence:string;due:string};
const baseTasks:Task[]=[{id:'l',name:'听力训练',detail:'Cambridge 18 · Test 2 · Section 3',min:35,done:true},{id:'r',name:'阅读训练',detail:'True / False / Not Given',min:45,done:false},{id:'s',name:'口语训练',detail:'Part 2 · 观点展开',min:20,done:false},{id:'w',name:'写作训练',detail:'Task 2 · 提纲练习',min:30,done:false},{id:'v',name:'单词复习',detail:'12 个到期单词',min:15,done:true}];
const baseWords:Word[]=[{word:'substantial',zh:'大量的；显著的',def:'large in amount, value, or importance',collocation:'a substantial increase / substantial evidence',example:'There has been a substantial rise in the number of students studying abroad.',error:'曾误写为 substantional',sentence:'A substantial investment in education can improve social mobility.',due:'今天'},{word:'alleviate',zh:'缓解；减轻',def:'to make pain, problems, or suffering less severe',collocation:'alleviate pressure / alleviate poverty',example:'Better public transport could alleviate traffic congestion in large cities.',error:'',sentence:'',due:'今天'},{word:'inevitable',zh:'不可避免的',def:'certain to happen and impossible to avoid',collocation:'an inevitable consequence',example:'Some job displacement is an inevitable consequence of automation.',error:'',sentence:'',due:'8月27日'}];
const qs=[['Part 1','Do you enjoy learning English? Why or why not?'],['Part 2','Describe a skill you would like to learn. Explain what it is, why you want to learn it, how you would learn it, and how it would help you.'],['Part 3','How has technology changed the way people learn new skills?']];
function load<T>(key:string,fallback:T):T{try{const x=localStorage.getItem(key);return x?JSON.parse(x):fallback}catch{return fallback}}
export default function Home(){
 const [view,setView]=useState('home'),[tasks,setTasks]=useState(baseTasks),[words,setWords]=useState(baseWords),[word,setWord]=useState(0),[show,setShow]=useState(false),[qi,setQi]=useState(0),[answer,setAnswer]=useState(''),[records,setRecords]=useState<{q:string;score:number;date:string;logic:string}[]>([]),[note,setNote]=useState(''),[ready,setReady]=useState(false);
 useEffect(()=>{setTasks(load('ieltsTasks',baseTasks));setWords(load('ieltsWords',baseWords));setRecords(load('ieltsRecords',[]));setNote(localStorage.getItem('ieltsNote')||'');setReady(true)},[]);
 useEffect(()=>{if(ready){localStorage.setItem('ieltsTasks',JSON.stringify(tasks));localStorage.setItem('ieltsWords',JSON.stringify(words));localStorage.setItem('ieltsRecords',JSON.stringify(records));localStorage.setItem('ieltsNote',note)}},[ready,tasks,words,records,note]);
 const done=tasks.filter(t=>t.done).length,min=tasks.filter(t=>t.done).reduce((a,t)=>a+t.min,0),pct=Math.round(done/tasks.length*100);
 const rate=(kind:string)=>{const days=kind==='again'?1:kind==='good'?3:7;setWords(words.map((x,i)=>i===word?{...x,due:'+'+days+' 天'}:x));setWord((word+1)%words.length);setShow(false)};
 const save=()=>{if(!answer.trim())return;const count=answer.trim().split(/\s+/).length;setRecords([{q:qs[qi][1],score:Math.min(9,Math.max(5,Math.round(count/18)+5)),date:'刚刚',logic:answer.length>180?'结构完整：观点 → 原因 → 例子 → 影响':'建议补充例子和影响'},...records]);setAnswer('')};
 return <main className="app"><aside><div className="brand"><i>i</i><b>IELTS<em>7+</em></b></div><p className="system">个人训练系统</p><nav>{[['home','◫','概览'],['words','Aa','单词系统'],['speak','◌','口语训练']].map(x=><button className={view===x[0]?'active':''} onClick={()=>setView(x[0])} key={x[0]}><i>{x[1]}</i>{x[2]}</button>)}</nav><footer><p>CURRENT LEVEL</p><b>B1 <em>→</em> 7.0+</b><small>稳定积累，比冲刺更重要。</small></footer></aside><section className="content"><header><div><p className="eyebrow">MONDAY · AUGUST 24</p><h1>{view==='home'?'今天，继续向前。':view==='words'?'用得出的词，才是你的词。':'把想法，说成结构。'}</h1></div><b className="avatar">L</b></header>{view==='home'?<Dashboard tasks={tasks} update={setTasks} done={done} min={min} pct={pct} note={note} noteSet={setNote} words={()=>setView('words')}/>:view==='words'?<Words all={words} item={words[word]} reveal={show} setReveal={setShow} rate={rate}/>:<Speaking q={qs[qi]} next={()=>{setQi((qi+1)%qs.length);setAnswer('')}} answer={answer} setAnswer={setAnswer} save={save} records={records}/>}</section></main>
}
function Dashboard(p:{tasks:Task[];update:(x:Task[])=>void;done:number;min:number;pct:number;note:string;noteSet:(x:string)=>void;words:()=>void}){
 const week=[42,66,35,82,50,92,p.min];return <div className="layout"><section><div className="progress"><div><p className="eyebrow">TODAY'S PROGRESS</p><strong>{p.pct}<small>%</small></strong><p>{p.done} / {p.tasks.length} 项任务完成 · 专注 {p.min} 分钟</p></div><div className="ring" style={{'--p':String(p.pct*3.6)+'deg'} as React.CSSProperties}><b>{p.done}<small>/ {p.tasks.length}</small></b></div></div><div className="title"><div><p className="eyebrow">TODAY'S PLAN</p><h2>今日训练</h2></div><span>8月24日</span></div><div className="tasks">{p.tasks.map(t=><label className={t.done?'done':''} key={t.id}><input type="checkbox" checked={t.done} onChange={()=>p.update(p.tasks.map(x=>x.id===t.id?{...x,done:!x.done}:x))}/><b>{t.done?'✓':''}</b><div><strong>{t.name}</strong><small>{t.detail}</small></div><em>{t.min}m</em></label>)}</div><div className="review"><p className="eyebrow">END-OF-DAY NOTE</p><textarea value={p.note} onChange={e=>p.noteSet(e.target.value)} placeholder="今天最大的收获或问题是什么？"/><div><small>自动保存在本设备</small><b>保存复盘</b></div></div></section><aside className="right"><div className="card"><p className="eyebrow">STREAK</p><strong>12 <small>days</small></strong><p>你正在建立一套稳定的学习节奏。</p></div><div className="card chart"><strong>5.2<small>h</small></strong><p className="eyebrow">THIS WEEK</p><h3>学习时长</h3><div>{week.map((x,i)=><span key={i}><i className={i===6?'today':''} style={{height:String(x)+'%'}}></i><small>{['一','二','三','四','五','六','日'][i]}</small></span>)}</div></div><button className="due" onClick={p.words}><b>Aa</b><div><p className="eyebrow">DUE TODAY</p><strong>12 个单词待复习</strong><small>主动回忆，而不是重读。</small></div><em>→</em></button></aside></div>
}
function Words(p:{all:Word[];item:Word;reveal:boolean;setReveal:(x:boolean)=>void;rate:(x:string)=>void}){return <div className="feature"><section><div className="title"><div><p className="eyebrow">SPACED REPETITION</p><h2>到期复习 <span>{p.all.filter(x=>x.due==='今天').length}</span></h2></div><small>先回忆，再核对答案。</small></div><article className="word"><div><span>IELTS CORE</span><small>第 3 轮复习</small></div><h2>{p.item.word}</h2><p className="definition">{p.item.def}</p>{p.reveal?<div className="facts"><div><label>中文意思</label><p>{p.item.zh}</p></div><div><label>常用搭配</label><p>{p.item.collocation}</p></div><div><label>雅思例句</label><p>{p.item.example}</p></div>{p.item.error&&<div className="mistake"><label>我的易错点</label><p>{p.item.error}</p></div>}{p.item.sentence&&<div><label>我的造句</label><p>{p.item.sentence}</p></div>}</div>:<div className="recall"><label>先在脑中回答</label><p>它的中文意思是什么？你能说出一个常用搭配吗？</p><button className="primary" onClick={()=>p.setReveal(true)}>显示答案</button></div>}</article>{p.reveal&&<div className="rate"><span>这次记得如何？</span><button onClick={()=>p.rate('again')}>忘记了 <small>1天后</small></button><button onClick={()=>p.rate('good')}>记得 <small>3天后</small></button><button className="primary" onClick={()=>p.rate('easy')}>很轻松 <small>7天后</small></button></div>}</section><aside className="detail"><p className="eyebrow">YOUR WORD BANK</p><h3>{p.all.length} 个核心词</h3><p>每个词都带有搭配、例句与个人错误记录。</p><div className="mini">{p.all.map(x=><div key={x.word}><b>{x.word}</b><small>{x.due}</small></div>)}</div><button className="outline">+ 添加新单词</button></aside></div>}
function Speaking(p:{q:string[];next:()=>void;answer:string;setAnswer:(x:string)=>void;save:()=>void;records:{q:string;score:number;date:string;logic:string}[]}){return <div className="feature"><section><article className="prompt"><div><span>{p.q[0]}</span><button onClick={p.next}>换一题 ↻</button></div><p className="eyebrow">IELTS SPEAKING</p><h2>{p.q[1]}</h2></article><div className="frame"><p className="eyebrow">ANSWER FRAMEWORK</p><div><b>01<small>观点</small></b><i>→</i><b>02<small>原因</small></b><i>→</i><b>03<small>例子</small></b><i>→</i><b>04<small>影响</small></b></div></div><div className="answer"><label>你的回答 <small>输入后系统将记录本次练习</small></label><textarea value={p.answer} onChange={e=>p.setAnswer(e.target.value)} placeholder="Start with your point of view…"/><div><small>{p.answer.trim()?p.answer.trim().split(/\s+/).length:0} words</small><button className="primary" onClick={p.save}>保存本次回答</button></div></div></section><aside className="detail"><p className="eyebrow">RECENT RECORDS</p>{p.records.length?p.records.slice(0,3).map((x,i)=><article className="record" key={i}><span>{x.date} · 流利度 {x.score}/9</span><p>{x.q}</p><small>{x.logic}</small></article>):<div className="empty"><b>还没有记录</b><p>完成第一段回答后，这里会帮你追踪流利度、语法、重复词与逻辑结构。</p></div>}<div className="ai"><b>AI 评估接口已预留</b><p>后续可接入 API，进行更细的语法标注与 IELTS 评分。</p></div></aside></div>}
