'use client';
import {useEffect,useMemo,useState} from 'react';

type Category='listening'|'reading'|'speaking'|'writing'|'vocabulary'|'review'|'optional';
type TaskType='core'|'review'|'optional';
type Task={id:string;title:string;category:Category;description:string;targetMinutes:number;completed:boolean;type:TaskType};
type DailyPlan={date:string;tasks:Task[]};
type StudySession={id:string;taskId:string;category:Category;startTime:string;endTime:string;duration:number;date:string};
type ActiveStudy={id:string;taskId:string;category:Category;startTime:string;accumulatedSeconds:number;isRunning:boolean};
type DailyReview={date:string;completed:string;problem:string;tomorrow:string};
type Word={word:string;zh:string;def:string;collocation:string;example:string;error:string;sentence:string;due:string};

const weekDays=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
const baseWords:Word[]=[{word:'substantial',zh:'大量的；显著的',def:'large in amount, value, or importance',collocation:'a substantial increase / substantial evidence',example:'There has been a substantial rise in the number of students studying abroad.',error:'曾误写为 substantional',sentence:'A substantial investment in education can improve social mobility.',due:'今天'},{word:'alleviate',zh:'缓解；减轻',def:'to make pain, problems, or suffering less severe',collocation:'alleviate pressure / alleviate poverty',example:'Better public transport could alleviate traffic congestion in large cities.',error:'',sentence:'',due:'今天'},{word:'inevitable',zh:'不可避免的',def:'certain to happen and impossible to avoid',collocation:'an inevitable consequence',example:'Some job displacement is an inevitable consequence of automation.',error:'',sentence:'',due:'8月27日'}];
const defaultTasks:Task[]=[
 {id:'listening',title:'听力训练',category:'listening',description:'Cambridge 18 · Test 2 · Section 3',targetMinutes:60,completed:false,type:'core'},
 {id:'reading',title:'阅读训练',category:'reading',description:'True / False / Not Given',targetMinutes:60,completed:false,type:'core'},
 {id:'speaking',title:'口语训练',category:'speaking',description:'Part 2 · 观点展开',targetMinutes:45,completed:false,type:'core'},
 {id:'writing',title:'写作训练',category:'writing',description:'Task 2 · 提纲练习',targetMinutes:45,completed:false,type:'core'},
 {id:'vocabulary',title:'单词复习',category:'vocabulary',description:'到期单词与主动回忆',targetMinutes:30,completed:false,type:'review'},
 {id:'mistakes',title:'昨日错误复习',category:'review',description:'回看错题、语法与表达记录',targetMinutes:20,completed:false,type:'review'}];
function localDate(date=new Date()){const offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,10)}
function load<T>(key:string,fallback:T):T{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}}
function formatMinutes(seconds:number){const total=Math.floor(seconds/60),h=Math.floor(total/60),m=total%60;return h?h+'h '+m+'m':m+'m'}
function clock(seconds:number){return Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0')}
function dateHeading(){return new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date()).toUpperCase()}
function initialPlan(date:string):DailyPlan{return {date,tasks:defaultTasks.map(x=>({...x}))}}

export default function Home(){
 const today=localDate(),planKey='ielts-plan-'+today,reviewKey='ielts-review-'+today;
 const [route,setRoute]=useState<'home'|'words'|'training'>('home'),[plan,setPlan]=useState<DailyPlan>({date:today,tasks:defaultTasks}),[sessions,setSessions]=useState<StudySession[]>([]),[active,setActive]=useState<ActiveStudy|null>(null),[review,setReview]=useState<DailyReview>({date:today,completed:'',problem:'',tomorrow:''}),[now,setNow]=useState(Date.now()),[words,setWords]=useState(baseWords),[word,setWord]=useState(0),[reveal,setReveal]=useState(false),[editing,setEditing]=useState<string|null>(null),[notice,setNotice]=useState(''),[ready,setReady]=useState(false);
 useEffect(()=>{setPlan(load(planKey,initialPlan(today)));setSessions(load('ielts-study-sessions',[]));setActive(load('ielts-active-study',null));setReview(load(reviewKey,{date:today,completed:'',problem:'',tomorrow:''}));setWords(load('ielts-words',baseWords));setReady(true)},[planKey,reviewKey,today]);
 useEffect(()=>{if(!ready)return;localStorage.setItem(planKey,JSON.stringify(plan));localStorage.setItem('ielts-study-sessions',JSON.stringify(sessions));localStorage.setItem('ielts-active-study',JSON.stringify(active));localStorage.setItem(reviewKey,JSON.stringify(review));localStorage.setItem('ielts-words',JSON.stringify(words))},[ready,planKey,plan,sessions,active,reviewKey,review,words]);
 useEffect(()=>{if(!active?.isRunning)return;const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(id)},[active?.isRunning]);
 const activeSeconds=active?(active.accumulatedSeconds+(active.isRunning?Math.max(0,Math.floor((now-new Date(active.startTime).getTime())/1000)):0)):0;
 const todaySessions=useMemo(()=>sessions.filter(x=>x.date===today),[sessions,today]);
 const secondsFor=(taskId:string)=>todaySessions.filter(x=>x.taskId===taskId).reduce((a,x)=>a+x.duration,0)+(active?.taskId===taskId?activeSeconds:0);
 const pause=()=>{if(!active?.isRunning)return;setActive({...active,accumulatedSeconds:activeSeconds,isRunning:false})};
 const resume=()=>{if(active&&!active.isRunning)setActive({...active,startTime:new Date().toISOString(),isRunning:true})};
 const finish=()=>{if(!active)return;const finalSeconds=activeSeconds;if(finalSeconds>0){const end=new Date();const session:StudySession={id:active.id,taskId:active.taskId,category:active.category,startTime:active.startTime,endTime:end.toISOString(),duration:finalSeconds,date:localDate(new Date(active.startTime))};setSessions([...sessions,session]);setPlan({...plan,tasks:plan.tasks.map(t=>t.id===active.taskId?{...t,completed:secondsFor(t.id)>=t.targetMinutes*60}:t)});setNotice('训练已保存，Dashboard 已同步真实学习时间。')}setActive(null);setNow(Date.now())};
 const startTask=(task:Task)=>{if(active&&active.taskId!==task.id){setNotice('请先结束当前计时，再开始另一项训练。');setRoute('home');return}if(active?.taskId===task.id){resume()}else{setActive({id:Date.now().toString(),taskId:task.id,category:task.category,startTime:new Date().toISOString(),accumulatedSeconds:0,isRunning:true})}setNotice('');setRoute(task.category==='vocabulary'?'words':'training')};
 const updateTask=(id:string,field:keyof Task,value:string|number|boolean)=>setPlan({...plan,tasks:plan.tasks.map(t=>t.id===id?{...t,[field]:value}:t)});
 const addOptional=()=>{const id='optional-'+Date.now();setPlan({...plan,tasks:[...plan.tasks,{id,title:'自定义训练',category:'optional',description:'例如：Shadowing / 英语视频',targetMinutes:20,completed:false,type:'optional'}]});setEditing(id)};
 const deleteOptional=(id:string)=>setPlan({...plan,tasks:plan.tasks.filter(t=>t.id!==id)});
 const rate=(mode:string)=>{const days=mode==='again'?1:mode==='good'?3:7;setWords(words.map((x,i)=>i===word?{...x,due:'+'+days+' 天'}:x));setWord((word+1)%words.length);setReveal(false)};
 const currentTask=active?plan.tasks.find(x=>x.id===active.taskId):plan.tasks.find(x=>x.category==='speaking');
 return <main className="app"><aside><div className="brand"><i>i</i><b>IELTS<em>7+</em></b></div><p className="system">个人训练系统</p><nav><button className={route==='home'?'active':''} onClick={()=>setRoute('home')}><i>◫</i>概览</button><button className={route==='words'?'active':''} onClick={()=>setRoute('words')}><i>Aa</i>单词系统</button><button className={route==='training'?'active':''} onClick={()=>setRoute('training')}><i>◌</i>口语训练</button></nav><footer><p>CURRENT TARGET</p><b>IELTS 7.0</b><small>Current estimate: B1</small></footer></aside><section className="content"><header><div><p className="eyebrow">{dateHeading()}</p><h1>{route==='home'?'今天，继续向前。':route==='words'?'用得出的词，才是你的词。':'专注这一段训练。'}</h1></div><button className="avatar" onClick={()=>setRoute('home')}>L</button></header>
 {route==='home'&&<Dashboard plan={plan} sessions={todaySessions} active={active} activeSeconds={activeSeconds} start={startTask} pause={pause} resume={resume} finish={finish} edit={editing} setEdit={setEditing} update={updateTask} addOptional={addOptional} deleteOptional={deleteOptional} review={review} setReview={setReview} notice={notice}/>}
 {route==='words'&&<Words all={words} item={words[word]} reveal={reveal} setReveal={setReveal} rate={rate} task={plan.tasks.find(x=>x.category==='vocabulary')} active={active} seconds={activeSeconds} start={startTask} pause={pause} resume={resume} finish={finish}/>}
 {route==='training'&&currentTask&&<Training task={currentTask} active={active} seconds={activeSeconds} start={startTask} pause={pause} resume={resume} finish={finish} back={()=>setRoute('home')} notice={notice}/>}
 </section></main>;
}

function Dashboard(p:{plan:DailyPlan;sessions:StudySession[];active:ActiveStudy|null;activeSeconds:number;start:(x:Task)=>void;pause:()=>void;resume:()=>void;finish:()=>void;edit:string|null;setEdit:(x:string|null)=>void;update:(id:string,f:keyof Task,v:string|number|boolean)=>void;addOptional:()=>void;deleteOptional:(id:string)=>void;review:DailyReview;setReview:(x:DailyReview)=>void;notice:string}){
 const elapsed=(task:Task)=>p.sessions.filter(x=>x.taskId===task.id).reduce((a,x)=>a+x.duration,0)+(p.active?.taskId===task.id?p.activeSeconds:0);
 const base=p.plan.tasks.filter(x=>x.type!=='optional'),totalTarget=base.reduce((a,x)=>a+x.targetMinutes*60,0),totalSeconds=p.sessions.reduce((a,x)=>a+x.duration,0)+p.activeSeconds,completed=p.plan.tasks.filter(x=>x.completed).length,pct=p.plan.tasks.length?Math.round(completed/p.plan.tasks.length*100):0;
 const categories:[Category,string][]=[['listening','Listening'],['reading','Reading'],['speaking','Speaking'],['writing','Writing']];
 const byType=(type:TaskType,label:string)=><section className="task-group" key={type}><div className="group-head"><div><p className="eyebrow">{type.toUpperCase()}</p><h2>{label}</h2></div>{type==='optional'&&<button className="outline" onClick={p.addOptional}>+ 添加增量训练</button>}</div>{p.plan.tasks.filter(x=>x.type===type).map(task=><TaskCard key={task.id} task={task} seconds={elapsed(task)} isActive={p.active?.taskId===task.id} editing={p.edit===task.id} edit={()=>p.setEdit(task.id)} close={()=>p.setEdit(null)} update={p.update} start={()=>p.start(task)} pause={p.pause} resume={p.resume} finish={p.finish} deleteTask={()=>p.deleteOptional(task.id)}/>)}</section>;
 return <div className="dashboard"><section className="dashboard-main"><div className="progress"><div><p className="eyebrow">TODAY'S PROGRESS</p><strong>{pct}<small>%</small></strong><p>{completed} / {p.plan.tasks.length} tasks · {formatMinutes(totalSeconds)} / {formatMinutes(totalTarget)}</p><div className="progress-breakdown">{categories.map(([id,label])=><span key={id}>{label} <b>{formatMinutes(p.sessions.filter(x=>x.category===id).reduce((a,x)=>a+x.duration,0)+(p.active?.category===id?p.activeSeconds:0))}</b></span>)}</div></div><div className="ring" style={{'--p':String(pct*3.6)+'deg'} as React.CSSProperties}><b>{completed}<small>/ {p.plan.tasks.length}</small></b></div></div>{p.notice&&<div className="dashboard-notice">{p.notice}</div>}{byType('core','核心任务')}{byType('review','复习任务')}{byType('optional','可选增量')}<DailyReviewBox review={p.review} update={p.setReview}/></section><DashboardRail sessions={p.sessions} active={p.active} activeSeconds={p.activeSeconds}/></div>;
}
function TaskCard(p:{task:Task;seconds:number;isActive:boolean;editing:boolean;edit:()=>void;close:()=>void;update:(id:string,f:keyof Task,v:string|number|boolean)=>void;start:()=>void;pause:()=>void;resume:()=>void;finish:()=>void;deleteTask:()=>void}){
 const reached=p.seconds>=p.task.targetMinutes*60;
 return <article className={'study-task '+(p.isActive?'running':'')}><div className="task-summary"><label><input type="checkbox" checked={p.task.completed} onChange={()=>{if(reached||p.task.completed)p.update(p.task.id,'completed',!p.task.completed)}}/><b>{p.task.completed?'✓':''}</b></label><div><strong>{p.task.title}</strong><small>{p.task.description}</small></div><button className="icon-btn" onClick={p.edit}>编辑</button></div>{p.editing?<div className="task-editor"><input value={p.task.title} onChange={e=>p.update(p.task.id,'title',e.target.value)}/><input value={p.task.description} onChange={e=>p.update(p.task.id,'description',e.target.value)}/><label>目标 <input type="number" min="5" value={p.task.targetMinutes} onChange={e=>p.update(p.task.id,'targetMinutes',Number(e.target.value)||0)}/> min</label><div><button className="outline" onClick={p.close}>完成编辑</button>{p.task.type==='optional'&&<button className="text-danger" onClick={p.deleteTask}>删除任务</button>}</div></div>:<div className="task-footer"><span>目标：{p.task.targetMinutes} min</span><span>已完成：<b>{formatMinutes(p.seconds)}</b></span><div>{p.isActive?<><button className="outline" onClick={p.pause}>暂停</button><button className="primary" onClick={p.finish}>结束并保存</button></>:<button className="primary" onClick={p.start}>{p.seconds?'继续训练':'开始训练'}</button>}</div></div>}</article>;
}
function DashboardRail(p:{sessions:StudySession[];active:ActiveStudy|null;activeSeconds:number}){
 const today=localDate(),monday=new Date();monday.setHours(0,0,0,0);monday.setDate(monday.getDate()-(monday.getDay()+6)%7);const daily=weekDays.map((_,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i);const key=localDate(d);return p.sessions.filter(x=>x.date===key).reduce((a,x)=>a+x.duration,0)});const weekTotal=daily.reduce((a,x)=>a+x,0);let streak=0;for(let i=0;i<365;i++){const d=new Date();d.setDate(d.getDate()-i);const key=localDate(d);const secs=p.sessions.filter(x=>x.date===key).reduce((a,x)=>a+x.duration,0);if(secs>=1800)streak++;else break}const max=Math.max(...daily,1);return <aside className="right"><div className="card"><p className="eyebrow">STREAK</p><strong>{streak} <small>days</small></strong><p>当天累计有效训练满 30 分钟，即计入连续学习。</p></div><div className="card chart"><strong>{formatMinutes(weekTotal)}</strong><p className="eyebrow">THIS WEEK</p><h3>学习时长</h3><div>{daily.map((seconds,i)=><span key={i}><i className={localDate()===localDate(new Date(monday.getFullYear(),monday.getMonth(),monday.getDate()+i))?'today':''} style={{height:String(Math.max(seconds?8:0,seconds/max*100))+'%'}}></i><small>{weekDays[i]}</small></span>)}</div></div><div className="card timer-card"><p className="eyebrow">STUDY TIMER</p>{p.active?<><strong>{clock(p.activeSeconds)}</strong><p>正在记录真实学习时间。</p></>:<><strong>0:00</strong><p>从任意任务点击“开始训练”。</p></>}</div></aside>;
}
function DailyReviewBox(p:{review:DailyReview;update:(x:DailyReview)=>void}){const set=(field:keyof DailyReview,value:string)=>p.update({...p.review,[field]:value});return <section className="daily-review"><p className="eyebrow">END-OF-DAY NOTE</p><div><label>今天完成了什么？<textarea value={p.review.completed} onChange={e=>set('completed',e.target.value)} placeholder="例如：完成了阅读 Passage 2 和 30 分钟复习。"/></label><label>今天最大的问题？<textarea value={p.review.problem} onChange={e=>set('problem',e.target.value)} placeholder="记录最需要修复的一个问题。"/></label><label>明天第一动作？<textarea value={p.review.tomorrow} onChange={e=>set('tomorrow',e.target.value)} placeholder="写下一个很具体、能立刻开始的动作。"/></label></div><small>自动按日期保存在本设备。</small></section>}
function Training(p:{task:Task;active:ActiveStudy|null;seconds:number;start:(x:Task)=>void;pause:()=>void;resume:()=>void;finish:()=>void;back:()=>void;notice:string}){const running=p.active?.taskId===p.task.id;return <div className="training-view"><button className="back" onClick={p.back}>← 返回 Dashboard</button><article><p className="eyebrow">{p.task.category.toUpperCase()} TRAINING</p><h2>{p.task.title}</h2><p>{p.task.description}</p><div className="focus-timer"><time>{clock(running?p.seconds:0)}</time><span>目标 {p.task.targetMinutes} min</span></div>{running?<div className="timer-actions"><button className="outline" onClick={p.pause}>暂停</button><button className="primary" onClick={p.finish}>结束并保存</button></div>:<button className="primary large" onClick={()=>p.start(p.task)}>{p.seconds?'继续训练':'开始训练'}</button>}<textarea placeholder="在这里记录训练要点、错题或下一步。"/></article></div>}
function Words(p:{all:Word[];item:Word;reveal:boolean;setReveal:(x:boolean)=>void;rate:(x:string)=>void;task:Task|undefined;active:ActiveStudy|null;seconds:number;start:(x:Task)=>void;pause:()=>void;resume:()=>void;finish:()=>void}){const running=p.active?.taskId===p.task?.id;return <div className="feature"><section>{p.task&&<div className="inline-timer"><div><p className="eyebrow">VOCABULARY SESSION</p><strong>{running?clock(p.seconds):'准备复习'}</strong></div>{running?<><button className="outline" onClick={p.pause}>暂停</button><button className="primary" onClick={p.finish}>结束</button></>:<button className="primary" onClick={()=>p.start(p.task!)}>开始计时</button>}</div>}<div className="title"><div><p className="eyebrow">SPACED REPETITION</p><h2>到期复习 <span>{p.all.filter(x=>x.due==='今天').length}</span></h2></div><small>先回忆，再核对答案。</small></div><article className="word"><div><span>IELTS CORE</span><small>第 3 轮复习</small></div><h2>{p.item.word}</h2><p className="definition">{p.item.def}</p>{p.reveal?<div className="facts"><div><label>中文意思</label><p>{p.item.zh}</p></div><div><label>常用搭配</label><p>{p.item.collocation}</p></div><div><label>雅思例句</label><p>{p.item.example}</p></div>{p.item.error&&<div className="mistake"><label>我的易错点</label><p>{p.item.error}</p></div>}{p.item.sentence&&<div><label>我的造句</label><p>{p.item.sentence}</p></div>}</div>:<div className="recall"><label>先在脑中回答</label><p>它的中文意思是什么？你能说出一个常用搭配吗？</p><button className="primary" onClick={()=>p.setReveal(true)}>显示答案</button></div>}</article>{p.reveal&&<div className="rate"><span>这次记得如何？</span><button onClick={()=>p.rate('again')}>忘记了 <small>1天后</small></button><button onClick={()=>p.rate('good')}>记得 <small>3天后</small></button><button className="primary" onClick={()=>p.rate('easy')}>很轻松 <small>7天后</small></button></div>}</section><aside className="detail"><p className="eyebrow">YOUR WORD BANK</p><h3>{p.all.length} 个核心词</h3><p>每个词都带有搭配、例句与个人错误记录。</p><div className="mini">{p.all.map(x=><div key={x.word}><b>{x.word}</b><small>{x.due}</small></div>)}</div></aside></div>}
