import {createEmptyCard,fsrs,generatorParameters,Rating,type CardInput,type Grade} from 'ts-fsrs';

export type ReviewRating='again'|'hard'|'good'|'easy';
export type ReviewItem={id:string;parentEntityId:string;sourceModule:'reading'|'listening'|'speaking'|'writing'|'vocabulary';sourceId:string;skill:'recognition'|'recall'|'listening'|'speaking'|'writing'|'logic'|'production'|'transfer';reviewType:string;prompt:string;answer:string;context:string;sourceWordId?:string;sourceDefinition?:string;sourceExample?:string;audioText?:string;audioUrl?:string;debugSource?:{sourceId:string;sourceType:string};difficultyLevel:number;masteryStage:number;fsrsCard:CardInput;createdAt:string;lastReviewedAt?:string;nextReviewAt:string;reviewCount:number;lapseCount:number;priority:number;isSuspended:boolean;buriedUntil?:string};
export type ReviewLog={id:string;reviewItemId:string;timestamp:string;rating:ReviewRating;correct:boolean;userAnswer:string;responseTimeMs:number;mistakeType:string;previousStage:number;nextStage:number;fsrsLog:unknown};
const scheduler=fsrs(generatorParameters({request_retention:.9,enable_fuzz:false,learning_steps:['10m','30m'],relearning_steps:['20m']}));
const iso=(d:Date|string)=>new Date(d).toISOString();
export const newReviewItem=(input:Omit<ReviewItem,'fsrsCard'|'createdAt'|'nextReviewAt'|'reviewCount'|'lapseCount'|'priority'|'isSuspended'>):ReviewItem=>{const now=new Date(),card=createEmptyCard(now);return {...input,fsrsCard:card,createdAt:now.toISOString(),nextReviewAt:iso(card.due),reviewCount:0,lapseCount:0,priority:0,isSuspended:false}};
export function scheduleReview(item:ReviewItem,rating:ReviewRating,answer:string,responseTimeMs:number,mistakeType:string){
 const correct=rating!=='again',grade={again:Rating.Again,hard:Rating.Hard,good:Rating.Good,easy:Rating.Easy}[rating] as Grade,result=scheduler.next(item.fsrsCard,new Date(),grade);
 const successful=correct?item.reviewCount+1:0;let stage=item.masteryStage;
 if(rating==='again')stage=Math.max(1,stage-1);else if(successful>=3&&rating!=='hard')stage=Math.min(5,stage+1);
 const updated:{[K in keyof ReviewItem]:ReviewItem[K]}={...item,fsrsCard:result.card,nextReviewAt:iso(result.card.due),lastReviewedAt:new Date().toISOString(),reviewCount:item.reviewCount+1,lapseCount:item.lapseCount+(correct?0:1),masteryStage:stage,priority:correct?0:2,buriedUntil:undefined};
 const log:ReviewLog={id:'log-'+Date.now(),reviewItemId:item.id,timestamp:new Date().toISOString(),rating,correct,userAnswer:answer,responseTimeMs,mistakeType,previousStage:item.masteryStage,nextStage:stage,fsrsLog:result.log};return {updated,log};
}
export function dueQueue(items:ReviewItem[],budgetMinutes:number){const now=Date.now(),bury=new Set<string>(),due=items.filter(x=>!x.isSuspended&&new Date(x.nextReviewAt).getTime()<=now&&(!x.buriedUntil||new Date(x.buriedUntil).getTime()<=now)).sort((a,b)=>new Date(a.nextReviewAt).getTime()-new Date(b.nextReviewAt).getTime()||b.priority-a.priority);const max=Math.max(4,Math.floor(budgetMinutes*1.5)),out:ReviewItem[]=[];let previous='';while(due.length&&out.length<max){let index=due.findIndex(x=>x.sourceModule!==previous&&!bury.has(x.parentEntityId));if(index<0)index=due.findIndex(x=>!bury.has(x.parentEntityId));if(index<0)break;const [item]=due.splice(index,1);out.push(item);previous=item.sourceModule;bury.add(item.parentEntityId)}return out}
export const feedback=(item:ReviewItem,answer:string)=>({correct:answer.trim().toLowerCase()===item.answer.trim().toLowerCase(),difference:answer.trim()&&answer.trim().toLowerCase()!==item.answer.trim().toLowerCase()?'Spelling, word form, or collocation differs from the expected answer.':'',example:item.context});
